//
//  PostListPresenter.swift
//  dynamic_table_view_tutorial
//
//  Created by 정정욱 on 7/8/24.
//  Copyright (c) 2024 Tuentuenna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostListPresentationLogic
{
    func presentPostList(response: PostList.FetchPostList.Response)
}

class PostListPresenter: PostListPresentationLogic
{
    weak var viewController: PostListDisplayLogic?
    
    // MARK: Do something
    // 인터렉터 -> 프리젠터로 온것
    // 날것의 데이터를 받음
    func presentPostList(response: PostList.FetchPostList.Response)  {
        
        typealias DisplayedPost = PostList.FetchPostList.ViewModel.DisplayedPost
        
        let displayedPosts = response.posts.map{DisplayedPost(post: $0)}
        
        let viewModel = PostList.FetchPostList.ViewModel(displayedPosts: displayedPosts) // 뷰모델에 넣어주면 됨
        
        // 그리고 해당 뷰모델을 뷰컨에게 넘겨주기
        viewController?.displayPostList(viewModel: viewModel)
    }
}
