//
//  PostListWorker.swift
//  dynamic_table_view_tutorial
//
//  Created by 정정욱 on 7/8/24.
//  Copyright (c) 2024 Tuentuenna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Fakery


// 외부 데이터 가져오기, API, 코어데이터, realm 등
class PostListWorker
{
    /// 포스트 리스트 가져오기
    /// - Returns: 가져온 포스트 배열
    func fetchPostList(count: Int) -> [Post]
    {
        let faker = Faker(locale: "ko")
        
        var postList : [Post] = []
        
        for _ in 0..<count {
            let dummyPost = Post(title: faker.company.name(), content: faker.lorem.paragraphs(amount: 10))
        
            
            postList.append(dummyPost)
        }
       
        return postList
    }
}
