//
//  PostListPresenter.swift
//  dynamic_table_view_tutorial
//
//  Created by 정정욱 on 7/8/24.
//  Copyright (c) 2024 Tuentuenna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol PostListPresentationLogic
{
  func presentSomething(response: PostList.Something.Response)
}

class PostListPresenter: PostListPresentationLogic
{
  weak var viewController: PostListDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: PostList.Something.Response)
  {
    let viewModel = PostList.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
}
