//
//  ListOrdersInteractor.swift
//  CleanStore
//
//  Created by Raymond Law on 2/12/19.
//  Copyright (c) 2019 Clean Swift LLC. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListOrdersBusinessLogic
{
  func fetchOrders(request: ListOrders.FetchOrders.Request)
}

protocol ListOrdersDataStore
{
  var orders: [Order]? { get }
}

class ListOrdersInteractor: ListOrdersBusinessLogic, ListOrdersDataStore
{
    
  // ⭐️ 2️⃣ interactor 한테 일을 시키면 presenter를 가지고 있어서
    // interactor 가 데이터베이스 worker 혹은 네트워킹 worker에게 접근해서 무언가를 가져오면 presenter에게 알려주는 것임 뭔가 데이터 변경되었다. 그러니까 너가 화면에 반영을 해라
  var presenter: ListOrdersPresentationLogic?
  
  var ordersWorker = OrdersWorker(ordersStore: OrdersMemStore())
  var orders: [Order]?
  
  // MARK: - Fetch orders
  
  func fetchOrders(request: ListOrders.FetchOrders.Request)
  {
      // 워커를 통해 데이터를 가져오면
    ordersWorker.fetchOrders { (orders) -> Void in
      self.orders = orders
      let response = ListOrders.FetchOrders.Response(orders: orders)
        self.presenter?.presentFetchedOrders(response: response) //프리젠터에게 알려주는것임 화면에 반영을해라
    }
  }
}
