//
//  PostListWorkerTests.swift
//  dynamic_table_view_tutorial
//
//  Created by 정정욱 on 7/9/24.
//  Copyright (c) 2024 Tuentuenna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import dynamic_table_view_tutorial
import XCTest

class PostListWorkerTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: PostListWorker!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupPostListWorker()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupPostListWorker()
  {
    sut = PostListWorker()
  }
  
  // MARK: Test doubles
  
  // MARK: Tests
  
  func testSomething()
  {
    // Given
    
    // When
    
    // Then
  }
}
