//
//  PostListPresenterTests.swift
//  dynamic_table_view_tutorial
//
//  Created by 정정욱 on 7/9/24.
//  Copyright (c) 2024 Tuentuenna. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import dynamic_table_view_tutorial
import XCTest

class PostListPresenterTests: XCTestCase
{
  // MARK: Subject under test
  
  var sut: PostListPresenter!
  
  // MARK: Test lifecycle
  
  override func setUp()
  {
    super.setUp()
    setupPostListPresenter()
  }
  
  override func tearDown()
  {
    super.tearDown()
  }
  
  // MARK: Test setup
  
  func setupPostListPresenter()
  {
    sut = PostListPresenter()
  }
  
  // MARK: Test doubles
  
  class PostListDisplayLogicSpy: PostListDisplayLogic
  {
    var displaySomethingCalled = false
    
    func displaySomething(viewModel: PostList.Something.ViewModel)
    {
      displaySomethingCalled = true
    }
  }
  
  // MARK: Tests
  
  func testPresentSomething()
  {
    // Given
    let spy = PostListDisplayLogicSpy()
    sut.viewController = spy
    let response = PostList.Something.Response()
    
    // When
    sut.presentSomething(response: response)
    
    // Then
    XCTAssertTrue(spy.displaySomethingCalled, "presentSomething(response:) should ask the view controller to display the result")
  }
}
